### ISSUE TITLE
Weird error in Production

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/emasjidmy-landing#31]
```
 ImageError: "url" parameter is valid but upstream response is invalid                                                                                                               │
│     at imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:588:19)                                                                                                │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32 {                                                                                                                     │
│   statusCode: 500                                                                                                                                                                   │
│ }                                                                                                                                                                                   │
│  ⨯ upstream image response failed for /images/Israa.jpg TypeError: fetch failed                                                                                                     │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)                                                                              │
│     at async /app/node_modules/next/dist/server/next-server.js:596:35                                                                                                               │
│     at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:576:13)                                                                                          │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32 {                                                                                                                     │
│   cause: SocketError: other side closed                                                                                                                                             │
│       at Socket.onSocketEnd (node:internal/deps/undici/undici:9169:26)                                                                                                              │
│       at Socket.emit (node:events:530:35)                                                                                                                                           │
│       at endReadableNT (node:internal/streams/readable:1696:12)                                                                                                                     │
│       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {                                                                                              │
│     code: 'UND_ERR_SOCKET',                                                                                                                                                         │
│     socket: {                                                                                                                                                                       │
│       localAddress: '::1',                                                                                                                                                          │
│       localPort: 34984,                                                                                                                                                             │
│       remoteAddress: undefined,                                                                                                                                                     │
│       remotePort: undefined,                                                                                                                                                        │
│       remoteFamily: undefined,                                                                                                                                                      │
│       timeout: undefined,                                                                                                                                                           │
│       bytesWritten: 6469,                                                                                                                                                           │
│       bytesRead: 784040                                                                                                                                                             │
│     }                                                                                                                                                                               │
│   }                                                                                                                                                                                 │
│ }
  ⨯ upstream image response failed for /images/eros.png TypeError: fetch failed                                                                                                      │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)                                                                              │
│     at async /app/node_modules/next/dist/server/next-server.js:596:35                                                                                                               │
│     at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:576:13)                                                                                          │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32 {                                                                                                                     │
│   cause: SocketError: other side closed                                                                                                                                             │
│       at Socket.onSocketEnd (node:internal/deps/undici/undici:9169:26)                                                                                                              │
│       at Socket.emit (node:events:530:35)                                                                                                                                           │
│       at endReadableNT (node:internal/streams/readable:1696:12)                                                                                                                     │
│       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {                                                                                              │
│     code: 'UND_ERR_SOCKET',                                                                                                                                                         │
│     socket: {                                                                                                                                                                       │
│       localAddress: '::1',                                                                                                                                                          │
│       localPort: 34990,                                                                                                                                                             │
│       remoteAddress: undefined,                                                                                                                                                     │
│       remotePort: undefined,                                                                                                                                                        │
│       remoteFamily: undefined,                                                                                                                                                      │
│       timeout: undefined,                                                                                                                                                           │
│       bytesWritten: 3792,                                                                                                                                                           │
│       bytesRead: 288399                                                                                                                                                             │
│     }                                                                                                                                                                               │
│   }                                                                                                                                                                                 │
│ }                                                                                                                                                                                   │
│ ImageError: "url" parameter is valid but upstream response is invalid                                                                                                               │
│     at imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:588:19)                                                                                                │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32 {                                                                                                                     │
│   statusCode: 500                                                                                                                                                                   │
│ }                                                                                                                                                                                   │
│ ImageError: "url" parameter is valid but upstream response is invalid                                                                                                               │
│     at imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:588:19)                                                                                                │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32 {                                                                                                                     │
│   statusCode: 500                                                                                                                                                                   │
│ }
```

**Comment by adamjanin** [comment]
@rohaizanr 
boleh check dekat cloudflare tak, sebab rasanya ni issue slowness dari sana

![image](https://github.com/Dev4w4n/emasjidmy-landing/assets/22977046/791df58f-ac64-440e-b67f-099f92e5a87c)

**Comment by rohaizanr** [comment]
@adamjanin di cloudflare takde benda sgt boleh setting dengan free account ni.

more clues..

```
⨯ upstream image response failed for /_next/static/media/feature3.0a1fb777.png ResponseAborted                                                                                     │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                   │
│     at async globalThis.fetch (/app/.next/server/chunks/638.js:1:36298)                                                                                                             │
│     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)                                                                              │
│     at async /app/node_modules/next/dist/server/next-server.js:596:35                                                                                                               │
│     at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:576:13)                                                                                          │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32                                                                                                                       │
│  ⨯ upstream image response failed for /_next/static/media/feature2.a6f91efd.png ResponseAborted                                                                                     │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                   │
│     at async globalThis.fetch (/app/.next/server/chunks/638.js:1:36298)                                                                                                             │
│     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)                                                                              │
│     at async /app/node_modules/next/dist/server/next-server.js:596:35                                                                                                               │
│     at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:576:13)                                                                                          │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32                                                                                                                       │
│  ⨯ upstream image response failed for /images/drsyam.png ResponseAborted                                                                                                            │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│  ⨯ upstream image response failed for /images/nazhan.jpg TypeError: fetch failed                                                                                                    │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                   │
│     at async globalThis.fetch (/app/.next/server/chunks/638.js:1:36298)                                                                                                             │
│     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)                                                                              │
│     at async /app/node_modules/next/dist/server/next-server.js:596:35                                                                                                               │
│     at async imageOptimizer (/app/node_modules/next/dist/server/image-optimizer.js:576:13)                                                                                          │
│     at async cacheEntry.imageResponseCache.get.incrementalCache (/app/node_modules/next/dist/server/next-server.js:176:65)                                                          │
│     at async /app/node_modules/next/dist/server/response-cache/index.js:90:36                                                                                                       │
│     at async /app/node_modules/next/dist/lib/batcher.js:41:32 {                                                                                                                     │
│   cause: ConnectTimeoutError: Connect Timeout Error                                                                                                                                 │
│       at onConnectTimeout (node:internal/deps/undici/undici:7760:28)                                                                                                                │
│       at node:internal/deps/undici/undici:7716:50                                                                                                                                   │
│       at Immediate._onImmediate (node:internal/deps/undici/undici:7748:13)                                                                                                          │
│       at process.processImmediate (node:internal/timers:478:21)                                                                                                                     │
│       at process.callbackTrampoline (node:internal/async_hooks:130:17) {                                                                                                            │
│     code: 'UND_ERR_CONNECT_TIMEOUT'                                                                                                                                                 │
│   }                                                                                                                                                                                 │
│ }
```

aku rasa next.js punya image optimizer ni

**Comment by rohaizanr** [comment]
```
⨯ upstream image response failed for /images/Israa.jpg ResponseAborted                                                                                                             │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│  ⨯ upstream image response failed for /images/fazreil.png ResponseAborted                                                                                                           │
│     at node:internal/deps/undici/undici:12618:11                                                                                                                                    │
│  ⨯ upstream image response failed for /images/adam.jpeg ResponseAborted                                                                                                             │
│     at node:internal/deps/undici/undici:12618:11 
```

**Comment by rohaizanr** [comment]
![Screenshot 2024-05-29 at 10 19 05 PM](https://github.com/Dev4w4n/emasjidmy-landing/assets/11247162/a5134fd0-9a39-4946-99b5-cb8ed04fc394)

ni pun boleh jadi jugak

**Comment by rohaizanr** [comment]
![Screenshot 2024-05-29 at 11 47 42 PM](https://github.com/Dev4w4n/emasjidmy-landing/assets/11247162/40d7e326-2170-4492-b830-95d8666dae27)

**Comment by rohaizanr** [comment]
kalau kata ada problem dengan cloudflare .... sini ok https://demo.e-masjid.my/web

**Comment by adamjanin** [comment]
cuba deploy image ni jap, aku ada ubah sikit config dia
https://github.com/Dev4w4n/emasjidmy-landing/pull/32

**Comment by rohaizanr** [comment]
```
Containers:                                                                                                                                                                         │
│   emasjid-landing-container:                                                                                                                                                        │
│     Container ID:   containerd://62ad3a52997b15257504a2020d65ece287e2cff92b0fc07799430a500c5878d8                                                                                   │
│     Image:          docker-registry:5000/emasjid-landing:1.10-beta.11b                                                                                                              │
│     Image ID:       docker-registry:5000/emasjid-landing@sha256:00a0f9cfa6bf9d661c6af056f7cfbda4d5b7c304826f6eea4ea53a7b42107926                                                    │
│     Port:           3000/TCP                                                                                                                                                        │
│     Host Port:      0/TCP                                                                                                                                                           │
│     State:          Running                                                                                                                                                         │
│       Started:      Thu, 30 May 2024 01:04:29 +0800                                                                                                                                 │
│     Last State:     Terminated                                                                                                                                                      │
│       Reason:       OOMKilled                                                                                                                                                       │
│       Exit Code:    137                                                                                                                                                             │
│       Started:      Thu, 30 May 2024 01:01:00 +0800                                                                                                                                 │
│       Finished:     Thu, 30 May 2024 01:04:14 +0800                                                                                                                                 │
│     Ready:          True                                                                                                                                                            │
│     Restart Count:  2                                                                                                                                                               │
│     Limits:                                                                                                                                                                         │
│       cpu:     100m                                                                                                                                                                 │
│       memory:  128Mi                                                                                                                                                                │
│     Requests:                                                                                                                                                                       │
│       cpu:        50m                                                                                                                                                               │
│       memory:     64Mi                                                                                                                                                              │
│     Environment:  <none>
```

jap try increase RAM

**Comment by rohaizanr** [comment]
@adamjanin 

```
 ▲ Next.js 14.2.3                                                                                                                                                                  │
│   - Local:        http://emasjid-landing-deployment-6cd5b68b96-fd5qd:3000                                                                                                           │
│   - Network:      http://10.1.101.243:3000                                                                                                                                          │
│                                                                                                                                                                                     │
│  ✓ Starting...                                                                                                                                                                      │
│  ✓ Ready in 606ms                                                                                                                                                                   │
│                                                                                                                                                                                     │
│ (process:1): VIPS-WARNING **: 17:11:58.104: threads clipped to 1024 
```

lain macam punya warning

**Comment by adamjanin** [comment]
aku tgk jap, lain macam error kali ni

**Comment by rohaizanr** [comment]
aku tambah CPU dgn RAM 

so far mcm ok

```
Containers:                                                                                                                                                                         │
│   emasjid-landing-container:                                                                                                                                                        │
│     Container ID:   containerd://315ee8dae2ce742ff019cb8efde38159086ccac545441771e69aa46100d38e35                                                                                   │
│     Image:          docker-registry:5000/emasjid-landing:1.15.5                                                                                                                     │
│     Image ID:       docker-registry:5000/emasjid-landing@sha256:a90e03ca91f64dc1c29ac9b802329cdc38ab0487e74dbf8bf07ef1b49740080a                                                    │
│     Port:           3000/TCP                                                                                                                                                        │
│     Host Port:      0/TCP                                                                                                                                                           │
│     State:          Running                                                                                                                                                         │
│       Started:      Thu, 30 May 2024 01:16:10 +0800                                                                                                                                 │
│     Ready:          True                                                                                                                                                            │
│     Restart Count:  0                                                                                                                                                               │
│     Limits:                                                                                                                                                                         │
│       cpu:     500m                                                                                                                                                                 │
│       memory:  256Mi                                                                                                                                                                │
│     Requests:                                                                                                                                                                       │
│       cpu:        250m                                                                                                                                                              │
│       memory:     128Mi                                                                                                                                                             │
│     Environment:  <none>
```

**Comment by adamjanin** [comment]
rasanya sebab kita guna **Next/Image** so dia ada auto image optimizer, ni la kot punca guna banyak resources. mungkin boleh disable function ni

**Comment by rohaizanr** [comment]
tapi dah ok. kita monitor dulu tengok.

kalau nanti resource tak cukup kita disable

**Comment by adamjanin** [comment]
okay, baik

**Comment by rohaizanr** [comment]
terima kasih
